import type { PCAgent } from '../types';

export const DEFAULT_AGENTS: Omit<PCAgent, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'agent_scout',
    name: 'Scout',
    pokemon: 'Eevee',
    pokemonId: '133',
    type: 'Knowledge Fetcher',
    typeIcon: '🔍',
    status: 'idle',
    progress: '0',
    isRunOnce: 'true',
    description: 'Fetches and indexes information from configured sources.',
    configJson: '{}',
  },
  {
    id: 'agent_taskmaster',
    name: 'Taskmaster',
    pokemon: 'Machamp',
    pokemonId: '68',
    type: 'Task Manager',
    typeIcon: '📋',
    status: 'idle',
    progress: '0',
    isRunOnce: 'false',
    description: 'Manages daily tasks and priorities. Syncs with task board and calendar.',
    configJson: '{}',
  },
  {
    id: 'agent_twitter',
    name: 'Twitter Bot',
    pokemon: 'Chatot',
    pokemonId: '441',
    type: 'Social Media',
    typeIcon: '🐦',
    status: 'idle',
    progress: '0',
    isRunOnce: 'false',
    description: 'Curates tweets from your feed, manages post queue, and tracks engagement.',
    configJson: JSON.stringify({
      accounts: ['naval', 'paulg', 'sama', 'patrickc', 'levelsio', 'elaboratemark', 'paborenstein'],
      keywords: ['startup advice', 'indie hacker', 'build in public'],
      maxPerAccount: 20,
      minLikes: 50,
    }),
  },
  {
    id: 'agent_linkedin',
    name: 'LinkedIn Bot',
    pokemon: 'Porygon',
    pokemonId: '137',
    type: 'Social Media',
    typeIcon: '💼',
    status: 'idle',
    progress: '0',
    isRunOnce: 'false',
    description: 'Manages LinkedIn post queue, scheduling, and engagement tracking.',
    configJson: '{}',
  },
  {
    id: 'agent_calendar',
    name: 'Celebi',
    pokemon: 'Celebi',
    pokemonId: '251',
    type: 'Scheduler',
    typeIcon: '📅',
    status: 'idle',
    progress: '0',
    isRunOnce: 'false',
    description: 'Manages your calendar events, scheduling, and Google Calendar sync.',
    configJson: '{}',
  },
  {
    id: 'agent_notes',
    name: 'Smeargle',
    pokemon: 'Smeargle',
    pokemonId: '235',
    type: 'Note Keeper',
    typeIcon: '📝',
    status: 'idle',
    progress: '0',
    isRunOnce: 'false',
    description: 'Manages notes, markdown editing, search, and version history.',
    configJson: '{}',
  },
  {
    id: 'agent_travel',
    name: 'Pidgeot',
    pokemon: 'Pidgeot',
    pokemonId: '18',
    type: 'Travel Agent',
    typeIcon: '✈️',
    status: 'idle',
    progress: '0',
    isRunOnce: 'false',
    description: 'Plans multi-leg itineraries, packing lists, and trip countdowns.',
    configJson: '{}',
  },
  {
    id: 'agent_gym',
    name: 'Primeape',
    pokemon: 'Primeape',
    pokemonId: '57',
    type: 'Trainer',
    typeIcon: '🏋️',
    status: 'idle',
    progress: '0',
    isRunOnce: 'false',
    description: 'Tracks gym workouts, metrics, and fitness progress.',
    configJson: '{}',
  },
  {
    id: 'agent_shopping',
    name: 'Meowth',
    pokemon: 'Meowth',
    pokemonId: '52',
    type: 'Shopkeeper',
    typeIcon: '🛒',
    status: 'idle',
    progress: '0',
    isRunOnce: 'false',
    description: 'Manages shopping lists with categories, quantities, and price tracking.',
    configJson: '{}',
  },
];

export const DEFAULT_LOGS: { agentId: string; level: string; message: string }[] = [];

export const DEFAULT_NOTIFICATIONS: { type: string; message: string; agentId: string }[] = [];

export const DEFAULT_TWITTER_POSTS: { content: string; status: string; scheduledAt: string; engagementLikes: string; engagementRetweets: string; engagementReplies: string }[] = [];

export const DEFAULT_LINKEDIN_POSTS: { content: string; status: string; scheduledAt: string; engagementLikes: string; engagementComments: string; engagementShares: string }[] = [];
