import type { PCAgent } from '../types';

export const DEFAULT_AGENTS: Omit<PCAgent, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'agent_scout',
    name: 'Scout',
    pokemon: 'Eevee',
    pokemonId: '133',
    type: 'Knowledge Fetcher',
    typeIcon: '🔍',
    status: 'completed',
    progress: '100',
    isRunOnce: 'true',
    description: 'Fetches and indexes information from configured sources.',
    configJson: '{}',
  },
  {
    id: 'agent_taskmaster',
    name: 'Taskmaster',
    pokemon: 'Machamp',
    pokemonId: '68',
    type: 'Task Manager',
    typeIcon: '📋',
    status: 'running',
    progress: '78',
    isRunOnce: 'false',
    description: 'Manages daily tasks and priorities. Syncs with task board and calendar.',
    configJson: '{}',
  },
  {
    id: 'agent_scribe',
    name: 'Scribe',
    pokemon: 'Alakazam',
    pokemonId: '65',
    type: 'Writer',
    typeIcon: '✍️',
    status: 'idle',
    progress: '0',
    isRunOnce: 'false',
    description: 'Generates documents, reports, and content on demand.',
    configJson: '{}',
  },
  {
    id: 'agent_sentinel',
    name: 'Sentinel',
    pokemon: 'Umbreon',
    pokemonId: '197',
    type: 'Monitor',
    typeIcon: '🛡️',
    status: 'running',
    progress: '55',
    isRunOnce: 'false',
    description: 'Watches for changes across configured sources and sends alerts.',
    configJson: '{}',
  },
  {
    id: 'agent_courier',
    name: 'Courier',
    pokemon: 'Pidgeot',
    pokemonId: '18',
    type: 'Messenger',
    typeIcon: '📨',
    status: 'idle',
    progress: '0',
    isRunOnce: 'false',
    description: 'Handles notifications, messages, and communication routing.',
    configJson: '{}',
  },
  {
    id: 'agent_analyst',
    name: 'Analyst',
    pokemon: 'Metagross',
    pokemonId: '376',
    type: 'Data Cruncher',
    typeIcon: '📊',
    status: 'running',
    progress: '65',
    isRunOnce: 'false',
    description: 'Processes data from Google Sheets and generates insights.',
    configJson: '{}',
  },
  {
    id: 'agent_twitter',
    name: 'Twitter Bot',
    pokemon: 'Chatot',
    pokemonId: '441',
    type: 'Social Media',
    typeIcon: '🐦',
    status: 'idle',
    progress: '0',
    isRunOnce: 'false',
    description: 'Manages Twitter/X post queue, scheduling, and engagement tracking.',
    configJson: '{}',
  },
  {
    id: 'agent_linkedin',
    name: 'LinkedIn Bot',
    pokemon: 'Porygon',
    pokemonId: '137',
    type: 'Social Media',
    typeIcon: '💼',
    status: 'idle',
    progress: '0',
    isRunOnce: 'false',
    description: 'Manages LinkedIn post queue, scheduling, and engagement tracking.',
    configJson: '{}',
  },
];

export const DEFAULT_LOGS = [
  { agentId: 'agent_scout', level: 'info', message: 'Fetched 24 documents from source A' },
  { agentId: 'agent_scout', level: 'info', message: 'Indexing complete. 24/24 processed.' },
  { agentId: 'agent_taskmaster', level: 'info', message: 'Synced 12 tasks from board' },
  { agentId: 'agent_taskmaster', level: 'info', message: 'Updated 3 priority items' },
  { agentId: 'agent_taskmaster', level: 'info', message: 'Scheduled 2 reminders' },
  { agentId: 'agent_sentinel', level: 'info', message: 'Monitoring 5 sources...' },
  { agentId: 'agent_sentinel', level: 'warn', message: 'Change detected in source B' },
  { agentId: 'agent_sentinel', level: 'info', message: 'Alert dispatched.' },
  { agentId: 'agent_analyst', level: 'info', message: 'Processing 1,200 rows...' },
  { agentId: 'agent_analyst', level: 'info', message: '800/1200 rows processed' },
];

export const DEFAULT_NOTIFICATIONS = [
  { type: 'alert', message: '2 new alerts since last visit', agentId: 'agent_sentinel' },
  { type: 'task', message: '3 tasks due today', agentId: 'agent_taskmaster' },
  { type: 'report', message: 'Weekly report ready to view', agentId: 'agent_analyst' },
  { type: 'info', message: 'Knowledge fetch completed — 24 new entries', agentId: 'agent_scout' },
  { type: 'info', message: '5 messages sent successfully', agentId: 'agent_courier' },
];

export const DEFAULT_TWITTER_POSTS = [
  { content: 'Thread about productivity systems and how I organize my digital life...', status: 'scheduled', scheduledAt: '15:00', engagementLikes: '0', engagementRetweets: '0', engagementReplies: '0' },
  { content: 'Quick tip: How I organize my day using a Pokemon Center as my command hub...', status: 'scheduled', scheduledAt: '18:00', engagementLikes: '0', engagementRetweets: '0', engagementReplies: '0' },
  { content: 'Reflection on this week\'s learning and automation experiments...', status: 'draft', scheduledAt: '', engagementLikes: '0', engagementRetweets: '0', engagementReplies: '0' },
  { content: 'Built a new automation today that handles all my task syncing across devices!', status: 'posted', scheduledAt: '', postedAt: new Date(Date.now() - 2 * 3600000).toISOString(), engagementLikes: '23', engagementRetweets: '5', engagementReplies: '3' },
  { content: 'Morning routine check — 4 tasks done before 9am. How are you starting your day?', status: 'posted', scheduledAt: '', postedAt: new Date(Date.now() - 8 * 3600000).toISOString(), engagementLikes: '24', engagementRetweets: '7', engagementReplies: '5' },
];

export const DEFAULT_LINKEDIN_POSTS = [
  { content: 'Lessons from building AI automation pipelines — what I learned after 3 months...', status: 'scheduled', scheduledAt: new Date(Date.now() + 24 * 3600000).toISOString(), engagementLikes: '0', engagementComments: '0', engagementShares: '0' },
  { content: 'How I restructured my workflow using gamification principles and why it doubled my output...', status: 'posted', scheduledAt: '', postedAt: new Date(Date.now() - 24 * 3600000).toISOString(), engagementLikes: '89', engagementComments: '12', engagementShares: '31' },
];
